import { AdminHandler } from "./handler/admin.handler";
import { AuthHandler } from "./handler/auth.handler";
import { BannisHandler } from "./handler/bannis.handler";
import { CandidateHandler } from "./handler/candidate.handler";
import { DegreeHandler } from "./handler/degree.handler";
import { EmployerHandler } from "./handler/employer.handler";
import { LocalisationHandler } from "./handler/localisation.handler";
import { PeriodHandler } from "./handler/period.handler";
import { ReportHandler } from "./handler/report.handler";
import { RoleHandler } from "./handler/role.handler";
import { TokenHandler } from "./handler/token.handler";
import { UserHandler } from "./handler/user.handler";
import { AdminRepository } from "./repository/admin.repository";
import { AuthRepository } from "./repository/auth.repository";
import { BannisRepository } from "./repository/bannis.repository";
import { CandidateRepository } from "./repository/candidate.repository";
import { DegreeRepository } from "./repository/degree.repository";
import { EmployerRepository } from "./repository/employer.repository";
import { LocalisationRepository } from "./repository/localisation.repository";
import { PeriodRepository } from "./repository/period.repository";
import { ReportRepository } from "./repository/report.repository";
import { RoleRepository } from "./repository/role.repository";
import { TokenRepository } from "./repository/token.repository";
import { UserRepository } from "./repository/user.repository";
import { AdminService } from "./services/admin.service";
import { AuthService } from "./services/auth.service";
import { BannisService } from "./services/bannis.service";
import { CandidateService } from "./services/candidate.service";
import { DegreeService } from "./services/degree.service";
import { EmailService } from "./services/email.service";
import { EmployerService } from "./services/employer.service";
import { LocalisationService } from "./services/localisation.service";
import { PeriodService } from "./services/period.service";
import { ReportService } from "./services/report.service";
import { RoleService } from "./services/role.service";
import { TokenService } from "./services/token.service";
import { UserService } from "./services/user.service";

export const adminHandler = new AdminHandler(new AdminService(new AdminRepository()));
export const userHandler = new UserHandler(new UserService(new UserRepository()));
export const tokenHandler = new TokenHandler(new TokenService(new TokenRepository()));
export const roleHandler = new RoleHandler(new RoleService(new RoleRepository()));
export const periodHandler = new PeriodHandler(new PeriodService(new PeriodRepository()));
export const localisationHandler = new LocalisationHandler(new LocalisationService(new LocalisationRepository()));
export const degreeHandler = new DegreeHandler(new DegreeService(new DegreeRepository()));
export const authHandler = new AuthHandler(new AuthService(new AuthRepository()), new EmailService(null));
export const candidateHandler = new CandidateHandler(new CandidateService(new CandidateRepository(), new UserRepository()));
export const employerHandler = new EmployerHandler(new EmployerService(new EmployerRepository(), new UserRepository()));
export const bannisHandler = new BannisHandler(new BannisService(new BannisRepository()));
export const reportHandler = new ReportHandler(new ReportService(new ReportRepository()));
